const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={back:'<path d="m14 5-7 7 7 7"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v13H4z"/><circle cx="12" cy="13" r="4"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>',link:'<path d="m9 15 6-6m-8 4-2 2a4 4 0 0 0 6 6l3-3m3-7 2-2a4 4 0 0 0-6-6l-3 3"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>',tree:'<path d="m12 2-6 8h3l-5 7h7v5h2v-5h7l-5-7h3z"/>',check:'<path d="m5 12 5 5L20 7"/>',plus:'<path d="M12 5v14M5 12h14"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',book:'<path d="M4 4h12a4 4 0 0 1 4 4v13H8a4 4 0 0 1-4-4zM4 17a4 4 0 0 1 4-4h12M8 4v9"/>',leaf:'<path d="M19 3C7 2 2 8 5 15c5 8 15 2 14-12zM4 21 15 9"/>',acorn:'<path d="M6 10c0 7 6 11 6 11s6-4 6-11M4 10h16c0-5-16-5-16 0zM12 6V2"/>',bench:'<path d="M4 5h16v7H4zM3 16h18M6 16v5m12-5v5M7 12v4m10-4v4"/>',moon:'<path d="M19 15A8 8 0 0 1 9 5a8 8 0 1 0 10 10z"/>'};
const icon=(name,size=21)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.leaf}</svg>`;
let extractionSequence=0;
let state={screen:'home',scenario:0,draft:null,source:'',method:'',schedule:null,status:'unrecorded',acorns:12,bench:false,error:'',confirmed:false};
const demoDraft=()=>({name:'Example medicine 10 mg tablets',strength:'10 mg',dose:'one tablet',route:'By mouth',directions:'Take ONE tablet by mouth at 08:00 every day.',frequency:'daily',times:['08:00'],needsClarification:false,timingSource:'prescription',sourceDirections:'Take ONE tablet by mouth at 08:00 every day.',rawText:'SYNTHETIC DEMO — NOT FOR MEDICAL USE\nExample medicine 10 mg tablets\nTake ONE tablet by mouth at 08:00 every day.'});
function forest(rest=false,bench=state.bench){
 const tree=(x,y,s,c='#617d58')=>`<g transform="translate(${x} ${y}) scale(${s})"><path d="M-6 5 0-90 7 5" fill="#775e44"/><path d="m0-119-35 57h17l-30 45h31L-40 3h80L18-17h30L18-62h17z" fill="${c}"/><path d="m0-119 4 121H40L18-17h30L18-62h17z" fill="#314e3d" opacity=".2"/></g>`;
 return `<svg class="forest" viewBox="0 0 400 280" role="img" aria-label="A green outdoor forest with a ${rest?'resting':'content'} squirrel. All trees are preserved."><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="${rest?'#e5e7dc':'#eaf0e6'}"/><stop offset="1" stop-color="#f5f2df"/></linearGradient></defs><path d="M0 0h400v280H0z" fill="url(#sky)"/><circle cx="319" cy="54" r="24" fill="${rest?'#f6edcb':'#f0d8a7'}"/><path d="M0 128q80-54 155-4t245-23v145H0" fill="#c4d1b4"/><path d="M0 154q110-58 205-6t195-12v125H0" fill="#a5b894"/>${tree(32,180,.8,'#90a580')}${tree(355,175,.9,'#809c78')}${tree(305,167,.65,'#99ad89')}${tree(87,173,.65,'#809a77')}<path d="M0 218q100-60 192-4t208-20v86H0" fill="#80956a"/><path d="M0 257q110-45 210-6t190-21v50H0" fill="#b9be8b"/><path d="M218 280q-3-26 36-49t39-26q-20 8-33 16t-84 59" fill="#ded0a8"/>${tree(181,225,1.47,'#526f4d')}${tree(46,232,.55,'#56734f')}${tree(337,229,.61,'#638154')}<g transform="translate(265 228)"><path d="M0 0c25-2 31-41 8-42-20-1-22 20-8 23 8 2 7-6 3-8 14-1 15 17-3 16" fill="#ac7040"/><ellipse cx="-7" cy="-4" rx="15" ry="12" fill="#b37a49"/><circle cx="-17" cy="-15" r="10" fill="#bd8955"/><path d="m-23-21 1-11 7 10m2 0 6-9 1 12" fill="#ad7244"/><ellipse cx="-21" cy="-11" rx="7" ry="5" fill="#dbc195"/>${rest?'<path d="m-22-16 5 1" stroke="#402c22" stroke-width="1.6"/>':'<circle cx="-20" cy="-17" r="1.5" fill="#402c22"/>'}<circle cx="-27" cy="-12" r="1.7" fill="#402c22"/><path d="m-15 5 11 1m1-1 9 1" stroke="#754c31" stroke-width="3" stroke-linecap="round"/></g>${bench?'<g transform="translate(71 239)" stroke="#735a3e" stroke-width="4"><path d="M0-16h36m-36 7h36m-39 9h42M3 0v11m30-11v11"/></g>':''}<g fill="#e7d9a8"><ellipse cx="77" cy="237" rx="3" ry="2"/><ellipse cx="312" cy="248" rx="3" ry="2"/><ellipse cx="116" cy="251" rx="2" ry="2"/><ellipse cx="353" cy="253" rx="3" ry="2"/></g><g stroke="#657e4f" stroke-width="2"><path d="m100 240 3-9 3 8m196-12 3-8 4 6m-279 21 3-7 3 5"/></g></svg>`;
}
const button=(label,action,style='',disabled=false)=>`<button class="action ${style}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const headerBar=(title='',back='home',step='')=>`<header class="topbar"><button class="icon-button" data-action="${back}" aria-label="Go back">${icon('back')}</button><span class="label">${title}</span><span class="step">${step||'acorn'}</span></header>`;
const progress=n=>`<div class="progress">${[1,2,3].map(i=>`<span class="${i<=n?'on':''}"></span>`).join('')}</div>`;
const nav=(sel='forest')=>`<nav class="bottomnav" aria-label="App navigation">${[['forest','tree','Forest','home'],['clearing','bench','Clearing','clearing'],['record','book','My record','record']].map(([id,i,l,a])=>`<button data-action="${a}" class="${sel===id?'selected':''}">${icon(i)}${l}</button>`).join('')}</nav>`;
const field=(label,key,value,helper='',readonly=false)=>`<label class="field"><span>${label}</span><input data-field="${key}" value="${esc(value)}" ${readonly?'readonly':''}>${helper?`<span class="helper">${helper}</span>`:''}</label>`;
function notes(){
const map={home:['One place to return to','The Forest is the home screen. A dose log and the growing world are one continuous experience.',['Earned, never bought','Only confirmed logs contribute to the personal record. Decorations do not unlock adherence milestones.'],['A clearing from day one','The squirrel lives outdoors. The Den becomes an accessible area of the same Forest.']],add:['Begin with what is available','Scanning a label is broadly available. Importing an exported record reduces typing when the record has enough detail.',['Fast path','Clear label → extract → review → confirm schedule. No account connection is needed to try it.'],['Honest integration','HealthHub PDF export exists. A direct production API connection is a separate access and partnership question.']],scan:['An actual local scan','Apple Vision reads a label image on this computer. PDF imports use embedded text first, with OCR for scanned pages.',['Data stays here','This prototype sends uploads only to its localhost server and deletes temporary upload files after reading.'],['Narrow parser','Only regular daily tablet or capsule directions (once to four times a day) can advance automatically to review. Other directions are held.']],review:['Evidence beside the draft','The original extracted directions remain visible. Each field is editable before a schedule can be saved.',['Recognition ≠ correctness','No model confidence badge is presented as medical certainty. Even a clean extraction needs confirmation.'],['Preserve meaning','Medicine strength and amount per dose are separate. Missing or complex directions block this shortcut.']],timing:['A schedule, with provenance','An explicit label time is carried forward. Without one, the user chooses a reminder time and sees that distinction.',['No timing invention','“Every eight hours” must never silently become breakfast, lunch and dinner.'],['Confirmation boundary','Nothing is scheduled until the final confirmation. This demo does not send notifications.']],rest:['A pause without a penalty','The Forest keeps its color and every earned tree. The squirrel rests comfortably in the same world.',['Accurate record','A missed dose is a recorded event. Lack of a log remains “not recorded” until clarified.'],['No catch-up advice','The app does not suggest doubling up, taking late, or waiting until tomorrow.']],records:['A practical import bridge','HealthHub lets users download medication records as a PDF. That can be imported now, without claiming direct API access.',['Currentness matters','Historical medication records are not automatically a current regimen. Ask the patient to confirm.'],['Separate future work','Authorized health-record integration can reduce typing later. It still needs reconciliation and patient review.']]};
const key=map[state.screen]?state.screen:['reading','held'].includes(state.screen)?'scan':['saved'].includes(state.screen)?'timing':'home';
const n=map[key];$('#annotations').innerHTML=`<div class="eyebrow">DESIGN REASONING</div><h3>${n[0]}</h3><p>${n[1]}</p>${n.slice(2).map((a,i)=>`<div class="annotation"><span class="number">0${i+1}</span><strong>${a[0]}</strong>${a[1]}</div>`).join('')}<div class="annotation"><strong>Prototype boundary</strong>OCR is functional. Health-record linking and device reminders are not connected. All preloaded medication data is synthetic.</div>`;
}
function render(){
const d=state.draft||demoDraft();let html='';
switch(state.screen){
case 'home':html=`<div class="body"><div class="home-head"><span class="overline">Your small daily ritual</span><button class="icon-button" data-action="add" aria-label="Add medication">${icon('plus')}</button></div><div class="home-title"><h2>Your forest.</h2><p class="sub">${state.status==='missed'?'Still here. Ready when you are.':'A little care, taking root.'}</p></div><div class="forest-wrap">${forest(state.status==='missed')}<div class="forest-overlay"><span>${state.status==='missed'?'Resting · progress preserved':'7 growth days · demo'}</span><span>${icon('acorn',12)} ${state.acorns} acorns</span></div></div><div class="milestone">${icon('tree',25)}<div><strong>Pine reached</strong><span style="float:right;color:var(--muted)">Next: oak · 14 days</span><div class="bar"><i></i></div></div></div><div class="section-heading"><h3>Today’s care</h3><button data-action="add">+ Add medicine</button></div>${state.schedule?`<div class="dose-card"><div class="meta"><span>${esc(state.schedule.times.join(' · '))} · ${state.schedule.intervalHours?'EVERY '+state.schedule.intervalHours+' HOURS':state.schedule.times.length>1?state.schedule.times.length+'× DAILY':'EVERY DAY'}${state.schedule.endDate?' · UNTIL '+esc(state.schedule.endDate):''}</span><span>${state.status==='taken'?'Logged as taken':state.status==='missed'?'Logged as missed':'Not recorded'}</span></div><strong>${esc(state.schedule.name)}</strong><p>${esc(state.schedule.dose)} · ${esc(state.schedule.route)}${state.schedule.instructions?' · '+esc(state.schedule.instructions):''}</p>${button(state.status==='unrecorded'?'Record dose':'View this dose','log',state.status==='taken'?'secondary':'')}</div>`:`<div class="dose-card"><div class="meta"><span>LET’S MAKE YOUR ROUTINE</span><span class="tag">Demo forest</span></div><strong>Your next step is a small one.</strong><p>Add a medicine to see your daily schedule here.</p>${button('Add your first medicine '+icon('arrow',17),'add')}</div>`}</div>${nav()}`;break;
case 'add':html=headerBar('Add a medicine')+progress(1)+`<div class="body"><span class="overline">Make room for your routine</span><h2>Start with your<br>prescription.</h2><p class="sub">We’ll help turn the details into a schedule you can check.</p><button class="option primary" data-action="scan"><span class="option-icon">${icon('camera')}</span><span><span class="tag intro-tag">Quickest to try</span><strong>Scan a prescription label</strong><small>Use a clear photo of your pharmacy label.</small></span><span class="arrow">${icon('arrow',17)}</span></button><button class="option" data-action="records"><span class="option-icon">${icon('file')}</span><span><strong>Import a medication PDF</strong><small>Use an exported record, including HealthHub.</small></span><span class="arrow">${icon('arrow',17)}</span></button><button class="option" data-action="manual"><span class="option-icon">${icon('book')}</span><span><strong>Enter the details yourself</strong><small>Keep your current prescription nearby.</small></span></button><p class="hint">${icon('shield',18)}You’ll review everything before it becomes a schedule.</p><button class="small-link" data-action="connected">About connecting health records</button></div>`;break;
case 'scan':html=headerBar('Scan a label','add','1 of 3')+progress(1)+`<div class="body"><span class="overline">Bring the details into view</span><h2>A photo.<br>A simpler start.</h2><p class="sub">Include the medicine name, strength and full directions. Use one medicine at a time.</p><div class="scanner"><img src="sample-label.png" alt="Fictional pharmacy label used to demonstrate scanning"><span class="scan-caption">Fictional demo label</span></div><p class="hint">${icon('camera',19)}Keep the label flat and well lit. You can retake it if any words are unclear.</p>${state.error?`<div class="error" role="alert">${esc(state.error)}</div>`:''}</div><div class="footer">${button(icon('camera',18)+' Choose a label photo','upload-image')}${button('Try the sample label','sample','secondary')}<p>Read locally on this Mac. No cloud upload.</p></div>`;break;
case 'reading':html=headerBar('Reading your file','add')+`<div class="body center"><div class="loader" aria-hidden="true"></div><h2>Finding the details.</h2><p class="sub" role="status">Reading the medicine name and directions. You’ll check them next.</p><div class="source-preview">${icon('shield',26)}<p style="margin-top:12px;font-size:12px">Your file is being processed locally.</p></div></div>`;break;
case 'review':html=headerBar('Review the details',state.source==='PDF'?'records':'scan','2 of 3')+progress(2)+`<div class="body"><span class="overline">A draft for you to check</span><h2>Does this match?</h2><p class="sub">Compare every detail with your current prescription. Edit anything that is wrong.</p><div class="source-preview"><div class="source-label">${esc(state.source||'MANUAL ENTRY')} · EXTRACTED DIRECTIONS</div><p>“${esc(d.sourceDirections||d.directions||'No directions found.')}”</p></div>${state.source==='PDF'?'<div class="notice warning"><strong>Reference record, not a prescription.</strong>Check that this medicine and these directions are still current.</div>':''}${field('Medicine and strength as written','name',d.name)}<div class="field-grid">${field('Strength','strength',d.strength)}${field('Amount per dose','dose',d.dose)}</div>${field('Route','route',d.route)}<label class="field"><span>Full directions</span><textarea data-field="directions">${esc(d.directions)}</textarea></label><div class="notice"><strong>Keep the original meaning.</strong>Regular daily doses (once to four times a day, or every 6, 8 or 12 hours) can be scheduled. As-needed, tapering or changing directions need clarification.</div>${(d.warningMessages||[]).map(w=>`<div class="notice warning"><strong>Check this.</strong>${esc(w)}</div>`).join('')}${(d.otherCandidates||[]).length?`<div class="notice"><strong>We also found other text that looks like a medicine.</strong>${esc(d.otherCandidates.join(' · '))} — make sure the name and strength above match your label.</div>`:''}<label class="check"><input type="checkbox" id="review-check"><span>I checked these details against my current prescription.</span></label>${state.error?`<div class="error" role="alert">${esc(state.error)}</div>`:''}<details><summary>View all extracted text</summary><pre>${esc(d.rawText||'Entered manually')}</pre></details></div><div class="footer">${button('Continue to schedule '+icon('arrow',17),'review-next','',true)}</div>`;break;
case 'choose':html=headerBar('Choose a medicine','add')+progress(2)+`<div class="body"><span class="overline">${state.choices.length} medicines found</span><h2>Which one first?</h2><p class="sub">This file lists more than one medicine. Set them up one at a time; you can come back for the others.</p><div class="timeline">${state.choices.map((m,i)=>`<button class="timeline-row choice" data-action="pick-${i}" style="width:100%;text-align:left;background:none;border:0;cursor:pointer"><span class="time">${m.needsClarification?'Check':(m.perDay?m.perDay+'× daily':'—')}</span><div><strong>${esc(m.name||'Name not found')}</strong><small>${esc(m.directions||'Directions not found')}</small></div></button>`).join('')}</div></div><div class="footer">${button('Back','add','secondary')}</div>`;break;
case 'held':html=headerBar('A little more clarity','add')+progress(2)+`<div class="body"><span class="overline">Nothing has been scheduled</span><h2>Let’s not guess.</h2><p class="sub">${esc((d.holdMessages&&d.holdMessages[0])||'These directions do not fit the regular daily schedule supported here.')}</p><div class="source-preview"><div class="source-label">DIRECTIONS FOUND</div><p>${esc(d.directions||'We could not reliably identify the directions.')}</p></div><div class="notice warning"><strong>No repeating reminder created.</strong>“As needed” directions do not become daily reminders. Changing or unclear directions also need a different setup. If any instruction is unclear, ask your pharmacist or care team to clarify it.</div><p class="hint">${icon('shield',18)}Your Forest is unchanged. No reminders or medication schedule have been created.</p><details><summary>View all extracted text</summary><pre>${esc(d.rawText)}</pre></details></div><div class="footer">${(state.choices||[]).length>1?button('Choose another medicine','choose'):button('Try a clearer label','scan')}${button('Back to my forest','home','secondary')}</div>`;break;
case 'timing':{const fixed=d.timingSource==='prescription';const n=d.times.length;html=headerBar('Your daily schedule','review','3 of 3')+progress(3)+`<div class="body"><span class="overline">One last check</span><h2>${fixed?(n>1?'Times to remember.':'A time to remember.'):(n>1?'Choose your times.':'Choose a reminder.')}</h2><p class="sub">${fixed?'These times were written in the directions. Check them before saving.':d.intervalHours?`Your directions say every ${d.intervalHours} hours. Choose your first dose; the others follow ${d.intervalHours} hours apart.`:`Your directions say ${n===1?'once':n+' times'} daily, without clock times. We suggested times; change them to fit your day. This does not change your prescribed instructions.`}</p><div class="source-preview"><div class="source-label">CURRENT DIRECTIONS</div><p>${esc(d.directions)}</p></div>${d.times.map((t,i)=>`<label class="field"><span>${n>1?'Dose '+(i+1)+' · ':''}${fixed?'Time from prescription':d.intervalHours?(i?d.intervalHours+' hours after the dose before':'Your first dose'):'Your reminder preference'}</span><input class="schedule-time" type="time" value="${esc(t)}" ${fixed||(d.intervalHours&&i)?'readonly':''}></label>`).join('')}<span class="helper">${fixed?'To correct a time, go back and correct the directions.':'Check any timing requirements, such as with food, with your pharmacist if unsure.'}</span><div class="timeline"><div class="timeline-row"><span class="time">${n>1?n+'× daily':'Daily'}</span><div><strong>${esc(d.name)}</strong><small>${esc(d.dose)} · ${esc(d.route)}${d.durationDays?' · for '+d.durationDays+' days':''}${d.instructions?' · '+esc(d.instructions):''}</small></div></div></div><label class="check"><input type="checkbox" id="schedule-check"><span>This is my current medicine and these details match my prescription.</span></label><p class="hint">${icon('clock',18)}The prototype saves a schedule for this session. Device notifications are not enabled.</p>${state.error?`<div class="error" role="alert">${esc(state.error)}</div>`:''}</div><div class="footer">${button('Confirm my schedule','save','',true)}</div>`;break}
case 'saved':html=headerBar('Ready for your routine','home')+`<div class="body center"><div class="big-tick">${icon('check',32)}</div><span class="overline">Schedule saved</span><h2>A little less<br>to remember.</h2><p class="sub">Your medicine now has a place in your daily routine.</p><div class="timeline-row" style="text-align:left;margin-top:30px"><span class="time">${esc(state.schedule.times.join(' · '))}</span><div><strong>${esc(state.schedule.name)}</strong><small>${esc(state.schedule.dose)} · every day</small></div></div><div class="forest-wrap" style="margin-top:25px">${forest()}</div></div><div class="footer">${button('Back to my forest','home')}${button('View schedule JSON','export','secondary')}</div>`;break;
case 'records':html=headerBar('Import a medication record','add','1 of 3')+progress(1)+`<div class="body"><span class="overline">Less typing, with a record</span><h2>Bring your<br>medication PDF.</h2><p class="sub">Download your medication record from HealthHub, then choose that PDF here.</p><div class="timeline"><div class="timeline-row"><span class="time">01</span><div><strong>Open HealthHub</strong><small>Go to medication records and select a record.</small></div></div><div class="timeline-row"><span class="time">02</span><div><strong>View details → download PDF</strong><small>Available records depend on your institution.</small></div></div><div class="timeline-row"><span class="time">03</span><div><strong>Import and check what is current</strong><small>Older records may not reflect your latest directions.</small></div></div></div><div class="notice warning"><strong>A record can be out of date.</strong>Confirm against your latest prescription. Missing directions or multiple medicines will need individual review.</div>${state.error?`<div class="error" role="alert">${esc(state.error)}</div>`:''}</div><div class="footer">${button(icon('file',18)+' Choose medication PDF','upload-pdf')}${button('Try the sample PDF','sample-pdf','secondary')}${button('Use a label photo instead','scan','light')}</div>`;break;
case 'connected':html=headerBar('Connect health records','add')+`<div class="body"><span class="tag">Future integration</span><h2>A connection<br>needs permission.</h2><p class="sub">A direct HealthHub or NEHR connection is not available in this prototype.</p><div class="notice"><strong>What works here today</strong>Import an exported PDF or scan a label, then check the details before saving.</div><p class="sub">A future connection would ask you to authorize a specific provider, select current medicines and resolve conflicting directions.</p><p class="hint">${icon('shield',18)}Acorn should never ask you to enter your Singpass password into this screen.</p></div><div class="footer">${button('Import a medication PDF','records')}${button('Scan a label','scan','secondary')}</div>`;break;
case 'log':{let med=state.schedule||demoDraft();html=headerBar('Record a dose')+`<div class="body"><span class="overline">Today’s care</span><h2>How did it go?</h2><p class="sub">Record what happened. You can correct it later.</p><div class="pill" aria-hidden="true"></div><div class="source-preview"><div class="source-label">${esc(med.times[0]||'08:00')} · ${state.schedule?'YOUR SCHEDULE':'SYNTHETIC DEMO'}</div><p><strong>${esc(med.name)}</strong></p><p class="sub">${esc(med.dose)} · ${esc(med.route)}</p></div><p class="hint">${icon('book',18)}This records a dose. Follow your prescription for how and when to take it.</p></div><div class="footer">${button('I took this dose','taken')}${button('I missed this dose','missed','secondary')}${button('Leave it unrecorded for now','home','light')}</div>`;break;}
case 'grown':html=headerBar('Dose recorded')+`<div class="body center"><span class="overline">A small moment of care</span><h2>Another day,<br>taking root.</h2><p class="sub">Recorded as taken. Your Forest keeps growing.</p><div class="forest-wrap" style="margin-top:25px">${forest()}</div><span class="balance" style="margin-top:25px">${icon('acorn',18)} +1 acorn earned</span><p class="hint" style="justify-content:center">A record of what you reported, kept with care.</p></div><div class="footer">${button('Return to my forest','home')}${button('Correct this log','log','secondary')}</div>`;break;
case 'rest':html=headerBar('Dose recorded')+`<div class="body center"><span class="overline">Your progress stays with you</span><h2>A quieter moment.</h2><p class="sub">This dose is recorded as missed.</p><div class="forest-wrap" style="margin-top:18px">${forest(true)}</div><h3 style="margin-top:23px">Everything you’ve grown<br>is still here.</h3><p class="sub" style="margin-top:15px">New growth is paused. Your squirrel is comfortable, and your Forest is yours.</p><div class="notice" style="text-align:left">For advice about a missed dose, check your medicine’s instructions or ask your pharmacist or care team.</div></div><div class="footer">${button('Return to my forest','home')}${button('Correct this log','log','secondary')}</div>`;break;
case 'clearing':html=`<div class="body"><div class="home-head"><span class="overline">A corner of your forest</span><span class="balance">${icon('acorn',15)}${state.acorns}</span></div><h2 style="margin-top:20px">Make yourself<br>at home.</h2><p class="sub">A little space for the things you like.</p><div class="forest-wrap">${forest(state.status==='missed')}</div><div class="section-heading"><h3>For your clearing</h3></div><div class="shop-grid"><button class="shop-item" data-action="bench" ${state.bench?'disabled':''}>${icon('bench',34)}<strong>${state.bench?'Bench placed':'A quiet bench'}</strong><small>${state.bench?'Yours to keep':'8 acorns'}</small></button><div class="shop-item">${icon('leaf',34)}<strong>Wildflower patch</strong><small>More choices in a future version</small></div></div><p class="hint">${icon('shield',18)}Decorations make this space yours. They don’t add growth days or change your medication record.</p></div>${nav('clearing')}`;break;
case 'export':html=headerBar('Structured schedule','record')+`<div class="body"><span class="overline">Your confirmed details</span><h2>A portable record.</h2><p class="sub">Select and copy the JSON below, or download it as a file. It includes source and reminder-time provenance.</p><label class="field"><span>Schedule JSON</span><textarea readonly style="min-height:420px;font:12px/1.6 monospace">${esc(JSON.stringify(state.schedule,null,2))}</textarea></label></div><div class="footer">${button('Download JSON file','download')}${button('Back to my forest','home','secondary')}</div>`;break;
case 'record':html=`<div class="body"><span class="overline">Your record, in your words</span><h2 style="margin-top:20px">Small steps,<br>honestly kept.</h2><p class="sub">A personal log of what you reported. This is not proof that medicine was taken.</p><div class="notice"><strong>${state.schedule?'1 medicine in this session':'No medicine saved yet'}</strong>${state.schedule?esc(state.schedule.name):'Add a medicine to begin your own record.'}</div><div class="timeline-row"><span class="time">Today</span><div><strong>${state.status==='taken'?'Recorded as taken':state.status==='missed'?'Recorded as missed':'No dose recorded'}</strong><small>${state.status==='unrecorded'?'Unrecorded is not the same as missed.':'Correct an entry whenever you need to.'}</small></div></div><div class="section-heading"><h3>Growth milestones</h3></div><p class="sub">Sprout · 1 day<br>Fern · 3 days<br>Pine · 7 days<br>Oak · 14 days<br>Cabin · 30 days</p><div class="notice">Milestones use cumulative completed care days in this concept. A miss pauses growth; it never erases an earned milestone. The calendar retains the gaps.</div>${state.schedule?button('View structured schedule','export','secondary'):button('Add a medicine','add')}</div>${nav('record')}`;break;
}
$('#app').innerHTML=html;$('#app').scrollTop=0;notes();$('#announcer').textContent=({review:'Review extracted medication details',held:'Schedule paused for clarification',saved:'Schedule saved',rest:'Missed dose recorded; forest preserved'})[state.screen]||'';
$('#scenarios').innerHTML=['Start & scan','Ambiguous directions','Missing clock time','Missed dose','Your clearing'].map((s,i)=>`<button class="scenario ${state.scenario===i?'active':''}" data-scenario="${i}"><span>0${i+1}</span>${s}<b>↗</b></button>`).join('');
}
function go(screen){state.screen=screen;state.error='';render()}
async function scan(file,source){const requestId=++extractionSequence;state.source=source;state.error='';go('reading');try{if(file.size>10*1024*1024)throw Error('Choose a file smaller than 10 MB.');const res=await fetch('/api/extract',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});const result=await res.json();if(requestId!==extractionSequence||state.screen!=='reading')return;if(!res.ok)throw Error(result.error||'Could not read this file.');state.method=result.method;state.choices=result.medicines||[result.draft];if(state.choices.length>1){go('choose');return}pick(0)}catch(error){if(requestId!==extractionSequence||state.screen!=='reading')return;state.screen=source==='PDF'?'records':'scan';state.error=error.message;render()}}
function collect(){document.querySelectorAll('[data-field]').forEach(el=>state.draft[el.dataset.field]=el.value.trim())}
function pick(i){state.draft={...state.choices[i]};state.draft.sourceDirections=state.draft.directions;go(state.draft.needsClarification?'held':'review')}
// The parsing rules live in label_parser.py; the server re-checks the edited draft so there is one source of truth.
async function reviewNext(){collect();let result;try{const res=await fetch('/api/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.draft)});result=await res.json();if(!res.ok)throw Error(result.error)}catch(error){state.error=error.message||'The details could not be checked.';render();return}state.draft={...state.draft,...result.draft};if(result.hold){go('held');return}if(result.error){state.error=result.error;render();return}go('timing')}
document.addEventListener('click',async e=>{const scenario=e.target.closest('[data-scenario]');if(scenario){state.scenario=Number(scenario.dataset.scenario);state.error='';if(state.scenario===0)go('add');if(state.scenario===1){state.draft={...demoDraft(),directions:'Take ONE tablet by mouth as needed.',times:[],needsClarification:true,rawText:'SYNTHETIC DEMO\nExample medicine 10 mg tablets\nTake ONE tablet by mouth as needed.'};state.source='Synthetic scenario';go('held')}if(state.scenario===2){state.draft={...demoDraft(),directions:'Take ONE tablet by mouth once daily.',times:[],timingSource:'patient_preference',rawText:'SYNTHETIC DEMO\nExample medicine 10 mg tablets\nTake ONE tablet by mouth once daily.'};state.draft.sourceDirections=state.draft.directions;state.source='Synthetic scenario';state.method='Synthetic scenario';go('review')}if(state.scenario===3)go('log');if(state.scenario===4)go('clearing');return}
const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;
if(a==='sample'||a==='sample-pdf'){try{const r=await fetch(a==='sample'?'sample-label.png':'sample-record.pdf');await scan(await r.blob(),a==='sample'?'Synthetic label':'PDF')}catch{state.error='Sample image could not be loaded.';render()}return}
if(a.startsWith('upload-')){$('#upload').accept=a==='upload-pdf'?'application/pdf':'image/png,image/jpeg,image/heic,image/webp';$('#upload').dataset.source=a==='upload-pdf'?'PDF':'Label photo';$('#upload').value='';$('#upload').click();return}
if(a==='manual'){state.source='Manual entry';state.method='Manual entry';state.draft={name:'',strength:'',dose:'',route:'',directions:'',times:[],rawText:''};go('review');return}
if(a==='review-next'){reviewNext();return}
if(a.startsWith('pick-')){pick(Number(a.slice(5)));return}
if(a==='save'){const times=[...document.querySelectorAll('.schedule-time')].map(el=>el.value);if(!times.length||times.some(t=>!t)){state.error='Choose a time for every dose to continue.';render();return}if(new Set(times).size!==times.length){state.error='Each dose needs a different time.';render();return}times.sort();const start=new Date();const days=state.draft.durationDays;state.schedule={schemaVersion:'0.1',name:state.draft.name,strength:state.draft.strength,dose:state.draft.dose,route:state.draft.route,originalDirections:state.draft.sourceDirections||state.draft.directions,confirmedDirections:state.draft.directions,frequency:state.draft.intervalHours?'every '+state.draft.intervalHours+' hours':times.length===1?'daily':times.length+' times daily',intervalHours:state.draft.intervalHours||null,instructions:state.draft.instructions||'',times,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,timingSource:state.draft.timingSource,source:{type:state.source,method:state.method||'Manual or synthetic scenario',extractedText:state.draft.rawText},patientConfirmedAt:new Date().toISOString(),status:'confirmed_by_patient',clinicalVerification:false,notificationsEnabled:false,startDate:start.toISOString().slice(0,10),endDate:days?new Date(start.getTime()+(days-1)*864e5).toISOString().slice(0,10):null};state.status='unrecorded';go('saved');return}
if(a==='taken'){if(state.status!=='taken')state.acorns++;state.status='taken';go('grown');return}
if(a==='missed'){if(state.status==='taken')state.acorns=Math.max(0,state.acorns-1);state.status='missed';go('rest');return}
if(a==='bench'){if(state.acorns>=8&&!state.bench){state.acorns-=8;state.bench=true;render()}return}
if(a==='download'){if(!state.schedule)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state.schedule,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='acorn-schedule.json';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);return}
go(a);
});
document.addEventListener('change',e=>{if(e.target.id==='review-check')document.querySelector('[data-action="review-next"]').disabled=!e.target.checked;if(e.target.id==='schedule-check')document.querySelector('[data-action="save"]').disabled=!e.target.checked;if(e.target.id==='upload'&&e.target.files[0])scan(e.target.files[0],e.target.dataset.source)});
document.addEventListener('input',e=>{if(e.target.matches('[data-field]')){state.draft[e.target.dataset.field]=e.target.value;const check=$('#review-check');if(check){check.checked=false;document.querySelector('[data-action="review-next"]').disabled=true}}});
render();

// Every-N-hours schedules: moving the first dose moves the rest, keeping the interval exact.
document.addEventListener('input',e=>{if(!e.target.classList.contains('schedule-time')||!state.draft||!state.draft.intervalHours)return;const inputs=[...document.querySelectorAll('.schedule-time')];if(e.target!==inputs[0]||!inputs[0].value)return;const [h,m]=inputs[0].value.split(':').map(Number);inputs.forEach((el,i)=>{const t=(h*60+m+i*state.draft.intervalHours*60)%1440;el.value=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0')})});
